/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Utils;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Admin
 */
public class SideMenu extends javax.swing.JPanel {

    private EventMenu event;

    /**
     * Creates new form SideMenu
     */
    public SideMenu() {
        initComponents();
        setOpaque(false);
        PanelMenu.setLayout(new MigLayout("wrap, fillx, inset 3", "[fill]", "[]0[]"));
    }

    public void initMenu(EventMenu event) {
        this.event = event;
        addMenu(new ImageIcon(getClass().getResource("/Icon/IconDatphong.png")), "Đặt Phòng", 0);
        addMenu(new ImageIcon(getClass().getResource("/Icon/IconKhachhang.png")), "Khách Hàng", 1);
        addMenu(new ImageIcon(getClass().getResource("/Icon/IconDichvu.png")), "Dịch Vụ", 2);
        addMenu(new ImageIcon(getClass().getResource("/Icon/IconNhanvien.png")), "Nhân Viên", 3);
        addMenu(new ImageIcon(getClass().getResource("/Icon/IconBill.png")), "Hóa Đơn", 4);
        addMenu(new ImageIcon(getClass().getResource("/Icon/IconDoanhthu.png")), "Doanh Thu", 5);
        //tang khoang cach
        addEmpty();
        addMenu(new ImageIcon(getClass().getResource("/Icon/logout.png")), "Đăng Xuất", 6);
    }

    private void addEmpty() {
        PanelMenu.add(new JLabel(), "push");
    }

    private void addMenu(Icon icon, String text, int index) {
        ButtonMenu menu = new ButtonMenu();
        menu.setIcon(icon);
        menu.setText("  " + text);
        PanelMenu.add(menu);
        menu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.selected(index);
                setSelected(menu);
            }
        });
    }

    //boi den khi da nhan
    private void setSelected(ButtonMenu menu) {
        //dung vong long for each de duyet tat ca cac nut
        //dua vao function addMenu cho bit dc nut nao dang dien ra su kien click !!
        for (Component com : PanelMenu.getComponents()) {
            if (com instanceof ButtonMenu) {
                ButtonMenu b = (ButtonMenu) com;
                //boi den
                b.setSelected(false);
            }
        }
        //con lai boi trang
        menu.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new Utils.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelMenu = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        panel2.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBorder(null);

        PanelMenu.setBackground(new java.awt.Color(51, 51, 51));
        PanelMenu.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelMenu);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private Utils.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
