/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;

import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

import Utils.DialogHelper;
import Utils.Encryption;

/**
 *
 * @author ACER
 */
public class ForgotJD extends javax.swing.JDialog {
	int randomcode;
	Connection con = null;
	ResultSet rs = null;
	PreparedStatement pst = null;
	public String user;
	public static String key = "MySecretKey12345";
	private Encryption encryption = new Encryption(key);

	public ForgotJD(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(null);
	}

	public ForgotJD(String username) {
		this.user = username;
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblAvatar = new javax.swing.JLabel();
		lblEmail = new javax.swing.JLabel();
		lblEmailIcon = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		btnXacNhan = new javax.swing.JButton();
		btnDoiMK = new javax.swing.JButton();
		lblEmail1 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		lblEmailIcon1 = new javax.swing.JLabel();
		txtEmail = new javax.swing.JTextField();
		txtCapcha = new javax.swing.JTextField();
		btnGuiThu = new javax.swing.JButton();
		lblEmail2 = new javax.swing.JLabel();
		lblEmailIcon2 = new javax.swing.JLabel();
		jSeparator3 = new javax.swing.JSeparator();
		lblEmail3 = new javax.swing.JLabel();
		lblEmailIcon3 = new javax.swing.JLabel();
		jSeparator4 = new javax.swing.JSeparator();
		btnCancel1 = new javax.swing.JButton();
		txtXacNhanMKM = new javax.swing.JPasswordField();
		txtMatKhauMoi = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-mailing.png"))); // NOI18N
		jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 100));

		lblEmail.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		lblEmail.setForeground(new java.awt.Color(0, 0, 0));
		lblEmail.setText("Mã xác nhận:");
		jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, -1));

		lblEmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-doimk1.png"))); // NOI18N
		jPanel1.add(lblEmailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, 50));

		jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
		jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 20));

		btnXacNhan.setBackground(new java.awt.Color(0, 95, 95));
		btnXacNhan.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
		btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tick.png"))); // NOI18N
		btnXacNhan.setText("Xác nhận");
		btnXacNhan.setBorder(null);
		btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXacNhanActionPerformed(evt);
			}
		});
		jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 130, 45));

		btnDoiMK.setBackground(new java.awt.Color(0, 95, 95));
		btnDoiMK.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		btnDoiMK.setForeground(new java.awt.Color(255, 255, 255));
		btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-update.png"))); // NOI18N
		btnDoiMK.setText("Đổi Mật Khẩu");
		btnDoiMK.setBorder(null);
		btnDoiMK.setEnabled(false);
		btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDoiMKActionPerformed(evt);
			}
		});
		jPanel1.add(btnDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 180, 45));

		lblEmail1.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		lblEmail1.setForeground(new java.awt.Color(0, 0, 0));
		lblEmail1.setText("Địa chỉ email:");
		jPanel1.add(lblEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

		jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
		jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 280, 20));

		lblEmailIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-email-sign.png"))); // NOI18N
		jPanel1.add(lblEmailIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 40));

		txtEmail.setBackground(new java.awt.Color(255, 255, 255));
		txtEmail.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
		txtEmail.setForeground(new java.awt.Color(0, 0, 0));
		txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
		txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				txtEmailFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				txtEmailFocusLost(evt);
			}
		});
		txtEmail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtEmailActionPerformed(evt);
			}
		});
		jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 40));

		txtCapcha.setBackground(new java.awt.Color(255, 255, 255));
		txtCapcha.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
		txtCapcha.setForeground(new java.awt.Color(0, 0, 0));
		txtCapcha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
		txtCapcha.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				txtCapchaFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				txtCapchaFocusLost(evt);
			}
		});
		jPanel1.add(txtCapcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 270, 40));

		btnGuiThu.setBackground(new java.awt.Color(0, 95, 95));
		btnGuiThu.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		btnGuiThu.setForeground(new java.awt.Color(255, 255, 255));
		btnGuiThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-send.png"))); // NOI18N
		btnGuiThu.setText("Gửi thư");
		btnGuiThu.setBorder(null);
		btnGuiThu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuiThuActionPerformed(evt);
			}
		});
		jPanel1.add(btnGuiThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 45));

		lblEmail2.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		lblEmail2.setForeground(new java.awt.Color(0, 0, 0));
		lblEmail2.setText("Mật khẩu:");
		jPanel1.add(lblEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, -1));

		lblEmailIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-doimk1.png"))); // NOI18N
		jPanel1.add(lblEmailIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 50));

		jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
		jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 20));

		lblEmail3.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		lblEmail3.setForeground(new java.awt.Color(0, 0, 0));
		lblEmail3.setText("Xác nhận mật khẩu:");
		jPanel1.add(lblEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 180, -1));

		lblEmailIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-doimk1.png"))); // NOI18N
		jPanel1.add(lblEmailIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 50));

		jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
		jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 280, 20));

		btnCancel1.setBackground(new java.awt.Color(0, 95, 95));
		btnCancel1.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
		btnCancel1.setForeground(new java.awt.Color(255, 255, 255));
		btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-update.png"))); // NOI18N
		btnCancel1.setText("Quay lại");
		btnCancel1.setBorder(null);
		btnCancel1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancel1ActionPerformed(evt);
			}
		});
		jPanel1.add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 130, 45));

		txtXacNhanMKM.setBackground(new java.awt.Color(255, 255, 255));
		txtXacNhanMKM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		txtXacNhanMKM.setForeground(new java.awt.Color(0, 0, 0));
		txtXacNhanMKM.setBorder(null);
		txtXacNhanMKM.setEnabled(false);
		jPanel1.add(txtXacNhanMKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 280, 39));

		txtMatKhauMoi.setBackground(new java.awt.Color(255, 255, 255));
		txtMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		txtMatKhauMoi.setForeground(new java.awt.Color(0, 0, 0));
		txtMatKhauMoi.setBorder(null);
		txtMatKhauMoi.setEnabled(false);
		jPanel1.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 280, 39));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXacNhanActionPerformed
//        if (Auth.checkNullText(txtEmail) && Auth.checkNullText(txtCapcha)) {
		if (Integer.valueOf(txtCapcha.getText()) == randomcode) {
			txtMatKhauMoi.setEnabled(true);
			txtXacNhanMKM.setEnabled(true);
			btnDoiMK.setEnabled(true);
			DialogHelper.alert(this, "Xác nhận thành công!!!");
		} else {
			DialogHelper.alert(this, "Mã code không đúng!!!");
		}
//        }
	}// GEN-LAST:event_btnXacNhanActionPerformed

	private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDoiMKActionPerformed
		if (txtMatKhauMoi.getText().equals(txtXacNhanMKM.getText())) {
			try {
				String update = "UPDATE TaiKhoan set TaiKhoan.MatKhau =? From TaiKhoan LEFT JOIN NhanVien on NhanVien.MaNV = TaiKhoan.MaNV  WHERE NhanVien.Email = ?";
				con = DriverManager.getConnection(
						"jdbc:sqlserver://localhost;databaseName=Dulieu;encrypt=false;user=sa;password=123");
				pst = con.prepareStatement(update);

				pst.setString(1, encryption.encrypt(txtXacNhanMKM.getText()));
				pst.setString(2, txtEmail.getText());
				pst.executeUpdate();

				DialogHelper.alert(this, "Đổi mật khẩu thành công");
//                dispose();
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else {
			DialogHelper.alert(this, "Đổi mật khẩu không thành công");
		}
	}// GEN-LAST:event_btnDoiMKActionPerformed

	private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtEmailFocusGained

	}// GEN-LAST:event_txtEmailFocusGained

	private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtEmailFocusLost

	}// GEN-LAST:event_txtEmailFocusLost

	private void txtCapchaFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCapchaFocusGained

	}// GEN-LAST:event_txtCapchaFocusGained

	private void txtCapchaFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCapchaFocusLost

	}// GEN-LAST:event_txtCapchaFocusLost

	private void btnGuiThuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuiThuActionPerformed
		try {

			Random rand = new Random();
			randomcode = rand.nextInt(999999);
			String host = "smtp.gmail.com";
			String user = "kienquocpro00@gmail.com";
			String pass = "jeuyyhemwihvsxlk";
			String To = txtEmail.getText();
			String Subject = "Thong tin mat khau - EduSys";
			String message = "Mã code xác nhận lại mật khẩu:" + randomcode;
			boolean sessionDebug = false;
			Properties props = new Properties();
			props.put("mail.smtp.host", "smtp.gmail.com");
			props.put("mail.smtp.port", "587");
			props.put("mail.smtp.auth", "true");
			props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
			props.put("mail.smtp.starttls.enable", "true");
			props.put("mail.smtp.starttls.required", "true");
			props.put("mail.smtp.host", "host");
			Session session = Session.getDefaultInstance(props, null);
			session.setDebug(sessionDebug);
			Message msg = new MimeMessage(session);

			msg.setFrom(new InternetAddress(user));
			InternetAddress[] address = { new InternetAddress(To) };
			msg.setRecipients(Message.RecipientType.TO, address);
			msg.setSubject(Subject);
			msg.setText(message);
			Transport tranport = session.getTransport("smtp");
			tranport.connect(host, user, pass);
			tranport.sendMessage(msg, msg.getAllRecipients());
			tranport.close();
			DialogHelper.alert(this, "Gửi mã thành công vui lòng kiểm tra email");
			btnGuiThu.setEnabled(false);
		} catch (Exception e) {
			System.out.println(e);
			DialogHelper.alert(this, "Gửi mã không thành công");
		}
	}// GEN-LAST:event_btnGuiThuActionPerformed

	public void DangNhap() {
		FormDangNhap formDangNhap = new FormDangNhap();
		formDangNhap.setVisible(true);
		this.setVisible(false);
	}

	private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEmailActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtEmailActionPerformed

	private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancel1ActionPerformed
		dispose();
		DangNhap();
	}// GEN-LAST:event_btnCancel1ActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancel1;
	private javax.swing.JButton btnDoiMK;
	private javax.swing.JButton btnGuiThu;
	private javax.swing.JButton btnXacNhan;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JLabel lblAvatar;
	private javax.swing.JLabel lblEmail;
	private javax.swing.JLabel lblEmail1;
	private javax.swing.JLabel lblEmail2;
	private javax.swing.JLabel lblEmail3;
	private javax.swing.JLabel lblEmailIcon;
	private javax.swing.JLabel lblEmailIcon1;
	private javax.swing.JLabel lblEmailIcon2;
	private javax.swing.JLabel lblEmailIcon3;
	private javax.swing.JTextField txtCapcha;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JPasswordField txtMatKhauMoi;
	private javax.swing.JPasswordField txtXacNhanMKM;
	// End of variables declaration//GEN-END:variables

}
