/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.NhanVien;
import Utils.DialogHelper;
import Utils.EventHeader;
import Utils.EventMenu;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormMain extends javax.swing.JFrame {

    public NhanVien nhanvien = null;

    public FormMain(NhanVien nhanVien) {
        initComponents();

        showpanel(new FormTrangChu());
        nhanvien = nhanVien;
        Event();
        ThongTinDangNhap();
    }

    public void Event() {
        setLocationRelativeTo(null);
        EventMenu event = new EventMenu() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    showpanel(new FormQLPhong(nhanvien));
                } //nut log out
                else if (index == 6) {
                    DangNhap();
                } //cac nut tuy theo minh chinh !!!!
                else if (index == 1) {
                    showpanel(new FormQuanLyKhachHang());
                } else if (index == 2) {
                    showpanel(new FormDichVuVaTienNghi());
                } else if (index == 3) {
                    showpanel(new FormNhanVien(nhanvien));
                } else if (index == 4) {
                    if (nhanvien.getVaiTro() == 0) {
                        DialogHelper.alert(new FormDangNhap(), "Ban Khong the xem muc nay !!!!");

                    } else {
                        showpanel(new FromHoaDon());
                    }
                } else if (index == 5) {
                    if (nhanvien.getVaiTro() == 0) {
                        DialogHelper.alert(new FormDangNhap(), "Ban Khong the xem muc nay !!!!");

                    } else {
                        showpanel(new FormDoanhThu());
                    }
                }
            }
        };
        EventHeader eventHeader = new EventHeader() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    showpanel(new FormTrangChu());
                } else {
                    System.out.println("thong bao");
                }
            }
        };
        header1.initMenu(eventHeader);
        sideMenu1.initMenu(event);
    }

    public void DangNhap() {
        FormDangNhap formDangNhap = new FormDangNhap();
        formDangNhap.setVisible(true);
        this.setVisible(false);
    }

    public void ThongTinDangNhap() {
        if (nhanvien != null) {

            header1.Hinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + nhanvien.getHinh()))); // NOI18N
            header1.lblTen.setText(nhanvien.getHoVaTen());
            header1.lblVaitro.setText(nhanvien.getHoVaTen());

            if (nhanvien.getVaiTro() == 0) {
//                MNIDoanhThuTungChuyenDe.setEnabled(false);
//                btnQuydinh.setEnabled(false);
                header1.lblVaitro.setText("Nhân Viên");
            } else {
//                MNIDoanhThuTungChuyenDe.setEnabled(true);
//                btnQuydinh.setEnabled(true);
                header1.lblVaitro.setText("Trưởng Phòng");
            }

        }
    }

    public boolean CheckTaiKhoanDangNhap() {
        if (nhanvien == null) {
            DialogHelper.alert(this, "Bạn Không Thể Sử Dụng Khi Chưa Đăng Nhập?");
            return false;
        }

        return true;
    }

    private void showpanel(Component pn) {
        body.removeAll();
        body.add(pn);
        body.revalidate();
        body.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sideMenu1 = new Utils.SideMenu();
        header1 = new Utils.Header();
        body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        body.setOpaque(false);
        body.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("© 2023-2025 KSF Vietnam JSC. All rights reserved.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1538, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sideMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(581, 581, 581))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addComponent(sideMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private Utils.Header header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private Utils.SideMenu sideMenu1;
    // End of variables declaration//GEN-END:variables
}
