/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.event.ActionListener;

import javax.swing.table.DefaultTableModel;

import Controller.ControllerTrangChu;
import Dao.DaoHoaDonPhong;
import Dao.DaoKhachHang;
import Dao.DaoPhong;
import Model.NhanVien;
import Model.Phong;
import PanelChart.ModelChart.chart.ModelChart;

/**
 *
 * @author Admin
 */
public class FormTrangChu extends javax.swing.JPanel {

	private String column[] = { "Họ Và Tên", "Check-in", "Check-out", "Loại Phòng" };
	private DefaultTableModel tblModel = new DefaultTableModel(column, 0);
	public DaoKhachHang daoKhachHang;
	public DaoPhong daophong;
	public DaoHoaDonPhong daoHoaDonPhong;

	public FormTrangChu() {
		initComponents();
		table();
		chart();
		Data();
		Action();

	}

	public void table() {
		table1.setModel(tblModel);
		table1.fixTable(scrollPaneWin111);
		daoKhachHang = new DaoKhachHang();
		daoKhachHang.LoadKHGanday(tblModel);
	}

	public void Data() {
		daophong = new DaoPhong();
		daoHoaDonPhong = new DaoHoaDonPhong(new FormDatPhong(new Phong(), new NhanVien()));
		lblSoPhong.setText(String.valueOf(daophong.CountALLPhong()));
		lbldatphongnow.setText(String.valueOf(daophong.CountDatPhong()));
		lblsldp.setText(String.valueOf(daoHoaDonPhong.CountALLPhong()));
		lbldpw.setText(String.valueOf(daoHoaDonPhong.CountSLDPW()));

	}

	public void RemoveChart() {
		lineChart.removeAll();
	}

	public void chart() {

		daoHoaDonPhong = new DaoHoaDonPhong(new FormDatPhong(new Phong(), new NhanVien()));
		lineChart.addLegend("Tuần này", new Color(255, 128, 0), new Color(255, 128, 0));
		lineChart.addLegend("Tuần trước", new Color(137, 230, 123), new Color(137, 230, 123));

		lineChart.addData(
				new ModelChart("Thứ 2", new double[] { daoHoaDonPhong.CountSLDD(2), daoHoaDonPhong.CountSLDDTT(2) }));
		lineChart.addData(
				new ModelChart("Thứ 3", new double[] { daoHoaDonPhong.CountSLDD(3), daoHoaDonPhong.CountSLDDTT(3) }));
		lineChart.addData(
				new ModelChart("Thứ 4", new double[] { daoHoaDonPhong.CountSLDD(4), daoHoaDonPhong.CountSLDDTT(4) }));
		lineChart.addData(
				new ModelChart("Thứ 5", new double[] { daoHoaDonPhong.CountSLDD(5), daoHoaDonPhong.CountSLDDTT(5) }));
		lineChart.addData(
				new ModelChart("Thứ 6", new double[] { daoHoaDonPhong.CountSLDD(6), daoHoaDonPhong.CountSLDDTT(6) }));
		lineChart.addData(
				new ModelChart("Thứ 7", new double[] { daoHoaDonPhong.CountSLDD(7), daoHoaDonPhong.CountSLDDTT(7) }));
		lineChart.addData(new ModelChart("Chủ Nhật",
				new double[] { daoHoaDonPhong.CountSLDD(1), daoHoaDonPhong.CountSLDDTT(1) }));
		lineChart.start();

	}

	public void Action() {
		ActionListener ac = new ControllerTrangChu(this);
		btnInExcel.addActionListener(ac);
		btnThang.addActionListener(ac);
		btnTuan.addActionListener(ac);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		lblsldp = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		lblSoPhong = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		lbldpw = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		lbldatphongnow = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		pnbooking = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		scrollPaneWin111 = new Utils.ScrollPaneWin11();
		table1 = new Utils.Table();
		btnInExcel = new Utils.Button();
		pnChartbooking = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		lineChart = new PanelChart.ModelChart.chart.LineChart();
		btnTuan = new Utils.Button();
		btnThang = new Utils.Button();

		jPanel1.setBackground(new java.awt.Color(234, 234, 250));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Iconnumberofbooking.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(208, 173, 240));
		jLabel3.setText("số lượng đặt phòng");

		lblsldp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		lblsldp.setForeground(new java.awt.Color(0, 0, 0));
		lblsldp.setText("0");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel3)
										.addContainerGap(137, Short.MAX_VALUE))
								.addGroup(jPanel2Layout.createSequentialGroup().addComponent(lblsldp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel2).addGap(19, 19, 19)))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel2).addComponent(lblsldp))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel3).addGap(20, 20, 20)));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		jPanel7.setBackground(new java.awt.Color(255, 255, 255));

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/IconBed.png"))); // NOI18N

		jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(208, 173, 240));
		jLabel6.setText("tổng số phòng");

		lblSoPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		lblSoPhong.setForeground(new java.awt.Color(0, 0, 0));
		lblSoPhong.setText("0");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblSoPhong).addComponent(jLabel6))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
						.addComponent(jLabel5).addContainerGap()));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addGap(18, 18, 18)
						.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel5)
								.addGroup(jPanel7Layout.createSequentialGroup().addComponent(lblSoPhong)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6)))
						.addContainerGap(14, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(39, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 17, Short.MAX_VALUE)));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));

		lbldpw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		lbldpw.setForeground(new java.awt.Color(0, 0, 0));
		lbldpw.setText("0");

		jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(208, 173, 240));
		jLabel9.setText("đặt phòng mỗi tuần");

		jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/IconCalender.png"))); // NOI18N

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel9)
										.addContainerGap(129, Short.MAX_VALUE))
								.addGroup(jPanel4Layout.createSequentialGroup().addComponent(lbldpw)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel10).addGap(15, 15, 15)))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(18, 18, 18)
										.addComponent(jLabel10).addGap(1, 1, 1))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(lbldpw)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
						.addComponent(jLabel9).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));

		jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(208, 173, 240));
		jLabel11.setText("đang đặt phòng");

		lbldatphongnow.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		lbldatphongnow.setForeground(new java.awt.Color(0, 0, 0));
		lbldatphongnow.setText("0");

		jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Iconbookingnow.png"))); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel5Layout.createSequentialGroup().addComponent(jLabel11)
										.addContainerGap(157, Short.MAX_VALUE))
								.addGroup(jPanel5Layout.createSequentialGroup().addComponent(lbldatphongnow)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel13).addGap(15, 15, 15)))));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel13)
								.addGap(1, 1, 1))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout.createSequentialGroup().addContainerGap().addComponent(lbldatphongnow)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
						.addComponent(jLabel11).addContainerGap(21, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(80, 80, 80)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(77, 77, 77)
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(14, 14, 14)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel6.setBackground(new java.awt.Color(249, 248, 248));

		pnbooking.setBackground(new java.awt.Color(255, 255, 255));
		pnbooking.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 0, 0));
		jLabel1.setText("Đặt Phòng Gần Đây");

		table1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { "aa", "aa", "aaa", "aa" }, { "aa", "aa", "aa", null },
								{ null, null, null, null }, { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		scrollPaneWin111.setViewportView(table1);

		btnInExcel.setBackground(new java.awt.Color(243, 243, 243));
		btnInExcel.setForeground(new java.awt.Color(0, 0, 0));
		btnInExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/IconExport.png"))); // NOI18N
		btnInExcel.setText("In File");
		btnInExcel.setBorderColor(new java.awt.Color(224, 224, 224));
		btnInExcel.setColorClick(new java.awt.Color(204, 204, 204));
		btnInExcel.setColorOver(new java.awt.Color(204, 204, 204));
		btnInExcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnInExcel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInExcelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnbookingLayout = new javax.swing.GroupLayout(pnbooking);
		pnbooking.setLayout(pnbookingLayout);
		pnbookingLayout.setHorizontalGroup(pnbookingLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnbookingLayout.createSequentialGroup().addGroup(pnbookingLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnbookingLayout.createSequentialGroup().addContainerGap().addComponent(
								scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
						.addGroup(pnbookingLayout.createSequentialGroup().addGap(15, 15, 15).addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnInExcel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		pnbookingLayout.setVerticalGroup(pnbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnbookingLayout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(pnbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(btnInExcel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
						.addContainerGap()));

		pnChartbooking.setBackground(new java.awt.Color(255, 255, 255));
		pnChartbooking.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(0, 0, 0));
		jLabel14.setText("Phân Tích Đặt Phòng (So Sánh)");

		jPanel8.setOpaque(false);

		lineChart.setOpaque(true);

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup()
						.addComponent(lineChart, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel8Layout.setVerticalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lineChart,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		btnTuan.setForeground(new java.awt.Color(51, 51, 51));
		btnTuan.setText("Tuần");
		btnTuan.setBorderColor(new java.awt.Color(255, 255, 255));
		btnTuan.setColorClick(new java.awt.Color(133, 133, 253));
		btnTuan.setColorOver(new java.awt.Color(133, 133, 253));
		btnTuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnTuan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTuanActionPerformed(evt);
			}
		});

		btnThang.setForeground(new java.awt.Color(51, 51, 51));
		btnThang.setText("Tháng");
		btnThang.setBorderColor(new java.awt.Color(255, 255, 255));
		btnThang.setColorClick(new java.awt.Color(133, 133, 253));
		btnThang.setColorOver(new java.awt.Color(133, 133, 253));
		btnThang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		btnThang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThangActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnChartbookingLayout = new javax.swing.GroupLayout(pnChartbooking);
		pnChartbooking.setLayout(pnChartbookingLayout);
		pnChartbookingLayout.setHorizontalGroup(pnChartbookingLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnChartbookingLayout.createSequentialGroup().addContainerGap().addGroup(pnChartbookingLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnChartbookingLayout.createSequentialGroup()
								.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(pnChartbookingLayout.createSequentialGroup().addGap(15, 15, 15).addComponent(jLabel14)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnTuan, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(btnThang, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(13, 13, 13)))));
		pnChartbookingLayout.setVerticalGroup(pnChartbookingLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnChartbookingLayout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(pnChartbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel14)
								.addComponent(btnTuan, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThang, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap(14, Short.MAX_VALUE)
						.addComponent(pnbooking, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pnChartbooking, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(14, 14, 14)));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(pnbooking, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pnChartbooking, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0).addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void btnThangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThangActionPerformed
		btnThang.setColor(new Color(133, 133, 253));
		btnThang.setForeground(new Color(255, 255, 255));
		btnTuan.setColor(new Color(255, 255, 255));
		btnTuan.setForeground(new Color(51, 51, 51));

	}// GEN-LAST:event_btnThangActionPerformed

	private void btnTuanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTuanActionPerformed
		btnTuan.setColor(new Color(133, 133, 253));
		btnTuan.setForeground(new Color(255, 255, 255));
		btnThang.setColor(new Color(255, 255, 255));
		btnThang.setForeground(new Color(51, 51, 51));

		lineChart.clear();
		lineChart.addData(
				new ModelChart("Thứ 2", new double[] { daoHoaDonPhong.CountSLDD(2), daoHoaDonPhong.CountSLDDTT(2) }));
		lineChart.addData(
				new ModelChart("Thứ 3", new double[] { daoHoaDonPhong.CountSLDD(3), daoHoaDonPhong.CountSLDDTT(3) }));
		lineChart.addData(
				new ModelChart("Thứ 4", new double[] { daoHoaDonPhong.CountSLDD(4), daoHoaDonPhong.CountSLDDTT(4) }));
		lineChart.addData(
				new ModelChart("Thứ 5", new double[] { daoHoaDonPhong.CountSLDD(5), daoHoaDonPhong.CountSLDDTT(5) }));
		lineChart.addData(
				new ModelChart("Thứ 6", new double[] { daoHoaDonPhong.CountSLDD(6), daoHoaDonPhong.CountSLDDTT(6) }));
		lineChart.addData(
				new ModelChart("Thứ 7", new double[] { daoHoaDonPhong.CountSLDD(7), daoHoaDonPhong.CountSLDDTT(7) }));
		lineChart.addData(new ModelChart("Chủ Nhật",
				new double[] { daoHoaDonPhong.CountSLDD(1), daoHoaDonPhong.CountSLDDTT(1) }));
		lineChart.start();
	}// GEN-LAST:event_btnTuanActionPerformed

	private void btnInExcelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInExcelActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnInExcelActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private Utils.Button btnInExcel;
	private Utils.Button btnThang;
	private Utils.Button btnTuan;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JLabel lblSoPhong;
	private javax.swing.JLabel lbldatphongnow;
	private javax.swing.JLabel lbldpw;
	private javax.swing.JLabel lblsldp;
	private PanelChart.ModelChart.chart.LineChart lineChart;
	private javax.swing.JPanel pnChartbooking;
	private javax.swing.JPanel pnbooking;
	private Utils.ScrollPaneWin11 scrollPaneWin111;
	private Utils.Table table1;
	// End of variables declaration//GEN-END:variables
}
